### ISSUE TITLE
Determine how/if to do Standups

### ISSUE THREAD

**Issue by kefortney** [VERSO-UVM/interactive-management-app#10]
Standups are often used to have the team check in for 15 minutes for each member to let the team know about any hurdles that they face or questions for the larger group. This task is to determine if the team wants to do these, and if so, when. 

This would be done on the selected communication methods (teams, slack, etc)

**Comment by kefortney** [comment]
Tuesday, not sure of time

**Comment by Alyssa4854** [comment]
We have settled on using the #standup channel in the team Slack for asynchronous standup once weekly.

- Post a few lines in the channel by each Wed at 8:00p EST.
- Briefly note progess on assigned work items/if there is anything blocking them
- If everything is going well just note **no roadblocks**
