### ISSUE TITLE
Create Test CSV Upload Datasets

### ISSUE THREAD

**Issue by kefortney** [VERSO-UVM/interactive-management-app#11]
As a developer I need a set of csv datasets that can be used to test the upload functionality for CSVs

**Description**
Create a folder in the repo called "test_data"

Files needed:
- set1.csv - list of unordered factor, 50 factors
- set2.csv - list of factors with an column that has a numeric value that is presorted in ascending order
- set3.csv - list of factors with an column that has a numeric value that is in a random order
- set4.csv - list of factors with an column that has a numeric float value that is in a random order
- set5.csv - list of unordered factor, 1000 factors (there will be repeating factors)
- set6.csv - list of factors with an column that has a numeric value that is in a random order where some numbers repeat

 **Notes**

- Should the headers should be included but not consistent?
- files should only be CSV, no tab delimited files
- order columns is only numeric but can have decimals
- what is the upper limit of factors?
- is the default resort ascending or descending?

**Comment by Fdeolive** [comment]
error handling for uploading CSV files

**Comment by kefortney** [comment]
Pushed files to Repo

**Comment by kefortney** [comment]
Files uploaded
