### ISSUE TITLE
Category data structure

### ISSUE THREAD

**Issue by Alyssa4854** [VERSO-UVM/Interactive-Management-App#37]
Given a problem the participants want to solve, they can break it down into steps (categories). Then they will be able to propose ideas for how to best handle a category/step.

- It should be a major component of how to solve the topic problem
- It will be a step/bubble in the diagram output

should probably contain data:
- title of the category (i.e. "Product accessibility", "How to sort x" ...)
- description of the category
- Ideas that have been proposed to solve the category
- if the category is solved yet/the solution

**Comment by gracekinney** [comment]
going to have a list of ideas for a class member
