### ISSUE TITLE
Explore Ranking and Selection Experiences

### ISSUE THREAD

**Issue by kefortney** [VERSO-UVM/interactive-management-app#7]
Once factors are added to the application we will need to rank them and select specific factors to work with users. Explore the user experience options for how other survey tools may select and rank items.

Present for 10 minutes at the Demo Meeting

**Comment by tasthana** [comment]
https://docs.google.com/document/d/1Bp5EJv1WFOe_vfs-kTSQJjR-AVUrHjleuJ-_F1bIGk0/edit?usp=sharing

**Comment by kefortney** [comment]
@tasthana please move this to Done and add the document created into the ORCA Slack #sprint-review channel
