### ISSUE TITLE
Set up Demo and Retrospective Meetings

### ISSUE THREAD

**Issue by kefortney** [VERSO-UVM/interactive-management-app#8]
At the end of the Sprint there needs to be a recorded meeting where team members demonstrate the work they have done so far and for the whole team to reflect on how the sprint could have been done better.  This task is the scheduling of this meeting with the team.

Kendall can provide zoom meeting details once scheduled

**Comment by kefortney** [comment]
8pm on thursday at end of sprint

**Comment by Alyssa4854** [comment]
Querying everyone's availability w/ calendly; we are moving retros from 8:00p on Tues due to conflicts

**Comment by Alyssa4854** [comment]
Polled availability and sent sprint planning + retro meetings for the rest of fall 2023 semester

Sprint planning is every other Wed at 8:00 - 9:00p EST
Sprint retro is every other Thurs at 8:00 - 9:00p EST
