### ISSUE TITLE
Setup SQLite Database

### ISSUE THREAD

**Issue by Alyssa4854** [VERSO-UVM/Interactive-Management-App#82]
Using SQLite3 for Python + SQLAlchemy for python

Create a database to store information about the researcher's work/and stuff

Things to do -

Think of tables we might need
Draft a schema
Implement a schema in SQLAlchemy

**Comment by ALIPHATICHYD** [comment]
Hello, @Alyssa4854 , I've read the contribution requirements and am excited to contribute to this issue.
