### ISSUE TITLE
Schedule Backlog Grooming Meeting 

### ISSUE THREAD

**Issue by kefortney** [VERSO-UVM/interactive-management-app#9]
We need to have a reoccurring meeting mid sprint to review open issues, add estimates of work, and order them in importance. This task is for scheduling that meeting.

Kendall can provide zoom credentials

**Comment by kefortney** [comment]
Wednesdays mid sprint at 7:30pm

**Comment by Alyssa4854** [comment]
Backlog grooming is currently set to 8:00 - 9:00p on every other Wed; will revisit if need be
